OPTIONS (SKIP=1)
LOAD DATA
    INFILE '/opt/optima/Interfaces/Configuration/parser/out/new_cm_exp.csv'
APPEND
INTO TABLE GLOBAL.CONF_CELL_4G_ERICSSON
FIELDS TERMINATED BY ";" OPTIONALLY ENCLOSED BY ','
TRAILING NULLCOLS
(
NAME,
TAC,
CI,
EARFCN,
PCI1 FILLER,
PCI2 FILLER,
PCI,
PRACH,
POWER,
DATETIME SYSDATE,
MOBCTRLATPOORCOVACTIVE
)
